VERSION        = 0.1
PORT_KEY       = "LIBRARIA_PORT"
DB_KEY_PATH    = "LIBRARIA_DB_PATH"
API_KEY_HEADER = "X-Auth"
DB_AUTH_TABLE  = "api_keys"

ENV[PORT_KEY] ||= "9821"
ENV[DB_KEY_PATH] ||= "./data.db"

KEY_LENGTH          = 11
PORT                = ENV[PORT_KEY].to_i
SQUEAL_LITE_DB_PATH = ENV[DB_KEY_PATH]
